on: 
  issues:
    types: [ opened ] # run this workflow only when a new issue is opened

jobs:
  create_issue_branch:
    runs-on: ubuntu-latest
    permissions: write-all # this workflow requires permissions to create branches and pull requests 
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}